import{a as E,S as p,i}from"./assets/vendor-c493984e.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const u of s.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&a(u)}).observe(document,{childList:!0,subtree:!0});function r(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function a(t){if(t.ep)return;t.ep=!0;const s=r(t);fetch(t.href,s)}})();function S(e){return`<li class="list-el">

 <a href="${e.largeImageURL}"><img src='${e.webformatURL}' alt='${e.tags}'></a>
  <div class="content">
    <div class="item"><h3>Likes</h3><p>${e.likes}</p></div>
    <div class="item"><h3>Views</h3><p>${e.views}</p></div>
    <div class="item"><h3>Comments</h3><p>${e.comments}</p></div>
    <div class="item"><h3>Downloads</h3><p>${e.downloads}</p></div>
 </div>
</li>
`}const w="https://pixabay.com/",q="api/",P="44530588-77e4763ebb7280f93ce94dd82";async function g(e,o){const r=new URLSearchParams({key:P,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:15}),a=`${w}${q}?${r}`,t={};return(await E.get(a,t)).data}let $=new p(".gallery a");const y=document.querySelector(".loader"),A=document.querySelector(".img-list"),f=document.querySelector("button[type=button]");d();n();const h={formElem:document.querySelector(".js-search-form"),articleListElem:document.querySelector(".js-article-list"),btnLoadMore:document.querySelector(".js-btn-load"),loadElem:document.querySelector(".js-loader")};let l="",c=1,v=0;h.formElem.addEventListener("submit",O);async function O(e){if(e.preventDefault(),l=e.target.elements.query.value.trim(),c=1,h.articleListElem.innerHTML="",!(l.trim()!=="")){d(),n(),i.error({message:"Info Search input must be filled!"});return}try{const r=await g(l,c);if(console.log(r),d(),r.total==0){n(),i.info({title:"Sorry,",message:"there are no images matching your search query. Please try again!"});return}v=r.total_pages,L(r.hits),R(),b(),r.hits.length<15?(n(),i.info({title:"info",message:"We're sorry, but you've reached the end of search results."})):m()}catch(r){i.error({title:"Error1",message:r.message})}}function j(e){return e.map(S).join("")}function L(e){const o=j(e);h.articleListElem.insertAdjacentHTML("beforeend",o),$.refresh()}function m(){y.classList.remove("visually-hidden")}function d(){y.classList.add("visually-hidden")}function R(){f.classList.remove("visually-hidden")}function n(){f.classList.add("visually-hidden")}new p(".gallery a",{captionDelay:250,captionsData:"alt"});f.addEventListener("click",async()=>{m(),c++;const e=await g(l,c);v=e.total_pages,L(e.hits),d(),b(),console.log(e.hits),console.log(e.hits),e.hits.length<15?(n(),i.info({title:"info",message:"We're sorry, but you've reached the end of search results."})):m()});function b(){const o=A.children[0].getBoundingClientRect().height;window.scrollBy({top:o*2,behavior:"smooth"})}
//# sourceMappingURL=commonHelpers.js.map
