import{a as E,S as p,i}from"./assets/vendor-c493984e.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))l(r);new MutationObserver(r=>{for(const s of r)if(s.type==="childList")for(const u of s.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&l(u)}).observe(document,{childList:!0,subtree:!0});function o(r){const s={};return r.integrity&&(s.integrity=r.integrity),r.referrerPolicy&&(s.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?s.credentials="include":r.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function l(r){if(r.ep)return;r.ep=!0;const s=o(r);fetch(r.href,s)}})();function S(e){return`<li class="list-el">

 <a href="${e.largeImageURL}"><img src='${e.webformatURL}' alt='${e.tags}'></a>
  <div class="content">
    <div class="item"><h3>Likes</h3><p>${e.likes}</p></div>
    <div class="item"><h3>Views</h3><p>${e.views}</p></div>
    <div class="item"><h3>Comments</h3><p>${e.comments}</p></div>
    <div class="item"><h3>Downloads</h3><p>${e.downloads}</p></div>
 </div>
</li>
`}const w="https://pixabay.com/",q="api/",P="44530588-77e4763ebb7280f93ce94dd82";async function v(e,t){const o=new URLSearchParams({key:P,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15}),l=`${w}${q}?${o}`,r={};return(await E.get(l,r)).data}let $=new p(".gallery a");const L=document.querySelector(".loader"),A=document.querySelector(".img-list"),h=document.querySelector("button[type=button]");a();n();const y={formElem:document.querySelector(".js-search-form"),articleListElem:document.querySelector(".js-article-list"),btnLoadMore:document.querySelector(".js-btn-load"),loadElem:document.querySelector(".js-loader")};let c="",d=1,m=0;y.formElem.addEventListener("submit",O);async function O(e){if(e.preventDefault(),c=e.target.elements.query.value.trim(),d=1,y.articleListElem.innerHTML="",!(c.trim()!=="")){a(),n(),i.error({message:"Info Search input must be filled!"});return}try{const o=await v(c,d);if(a(),o.total==0){n(),i.info({title:"Sorry,",message:"there are no images matching your search query. Please try again!"});return}m=o.total_pages,f(o.hits),b(),o.hits.length<15?(n(),i.info({title:"info",message:"We're sorry, but you've reached the end of search results."})):a()}catch(o){i.error({title:"Error1",message:o.message})}}function _(e){return e.map(S).join("")}function f(e){const t=_(e);y.articleListElem.insertAdjacentHTML("beforeend",t),$.refresh()}function j(){L.classList.remove("visually-hidden")}function a(){L.classList.add("visually-hidden")}function b(){h.classList.remove("visually-hidden")}function n(){h.classList.add("visually-hidden")}new p(".gallery a",{captionDelay:250,captionsData:"alt"});h.addEventListener("click",async()=>{j(),d++;try{const t=await v(c,d);if(a(),t.total==0){n(),i.info({title:"Sorry,",message:"there are no images matching your search query. Please try again!"});return}m=t.total_pages,f(t.hits),b(),g(),t.hits.length<15?(n(),i.info({title:"info",message:"We're sorry, but you've reached the end of search results."})):a()}catch(t){i.error({title:"Error1",message:t.message})}m=data.total_pages,f(data.hits),a(),g(),data.hits.length<15?(n(),i.info({title:"info",message:"We're sorry, but you've reached the end of search results."})):a()});function g(){const t=A.children[0].getBoundingClientRect().height;window.scrollBy({top:t*2,behavior:"smooth"})}
//# sourceMappingURL=commonHelpers.js.map
