import{a as v,S as p,i}from"./assets/vendor-c493984e.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))l(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const d of s.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&l(d)}).observe(document,{childList:!0,subtree:!0});function r(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function l(t){if(t.ep)return;t.ep=!0;const s=r(t);fetch(t.href,s)}})();function b(e){return`<li class="list-el">

 <a href="${e.largeImageURL}"><img src='${e.webformatURL}' alt='${e.tags}'></a>
  <div class="content">
    <div class="item"><h3>Likes</h3><p>${e.likes}</p></div>
    <div class="item"><h3>Views</h3><p>${e.views}</p></div>
    <div class="item"><h3>Comments</h3><p>${e.comments}</p></div>
    <div class="item"><h3>Downloads</h3><p>${e.downloads}</p></div>
 </div>
</li>
`}const S="https://pixabay.com/",w="api/",E="44530588-77e4763ebb7280f93ce94dd82",q=15;async function h(e,o){const r=new URLSearchParams({key:E,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:15}),l=`${S}${w}?${r}`,t={params:{q:e,page:o,page_size:q,per_page:15}};return console.log("shut down"),(await v.get(l,t)).data}let _=new p(".gallery a");const g=document.querySelector(".loader"),u=document.querySelector("button[type=button]");n();f();const m={formElem:document.querySelector(".js-search-form"),articleListElem:document.querySelector(".js-article-list"),btnLoadMore:document.querySelector(".js-btn-load"),loadElem:document.querySelector(".js-loader")};let c="",a=1,y=0;m.formElem.addEventListener("submit",P);async function P(e){if(e.preventDefault(),c=e.target.elements.query.value.trim(),a=1,m.articleListElem.innerHTML="",!(c.trim()!=="")){n(),f(),i.error({message:"Info Search input must be filled!"});return}try{const r=await h(c,a);n(),r.total==0&&i.info({title:"Sorry,",message:"there are no images matching your search query. Please try again!"}),y=r.total_pages,L(r.hits),n(),O()}catch(r){newsApi.totalResult=0,i.error({title:"Error1",message:r.message})}a==data.total_pages&&i.info({title:"info",message:"Were sorry, but you've reached the end of search results."})}function $(e){return e.map(b).join("")}function L(e){const o=$(e);m.articleListElem.insertAdjacentHTML("beforeend",o),_.refresh()}function A(){g.classList.remove("visually-hidden")}function n(){g.classList.add("visually-hidden")}function O(){u.classList.remove("visually-hidden")}function f(){u.classList.add("visually-hidden")}new p(".gallery a",{captionDelay:250,captionsData:"alt"});console.log("shut down");u.addEventListener("click",async()=>{A(),a++,console.log("load++++");const e=await h(c,a);y=e.total_pages,L(e.hits),n(),a==e.total_pages&&(i.info({title:"info",message:"Were sorry, but you've reached the end of search results."}),f())});
//# sourceMappingURL=commonHelpers.js.map
